language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ZSgft5+N5qUkeRrqCJFaZwAFc8GwYTCwDSBSe845lwmYxy/Fd6l9sDgowbnK7Tbq0Fk3uBUyCnG1fEqoDIlEjL97YSq5AORatT2GEuCoDURNzFLHnig+T5KDYGYu6gWklrGUgponXI5sr2ovUdOO9FCB+qRaVsFom+cxc/lfxbHhvibnBlCi0RJVRkQ7+YDZtitkzmUhTGpwEXjpbrQl1kPvJpiBpQdbeCwlvda5UJn1nL/Xh6e/HgqdktyN/l/WIlNGZHWC4SzAelo+THHJppJfcXFLohiRnYDgi85iFlOHknwTwsDxmRUbjnGp63owFERuMDdCZKiJcLTxpKMjgV7OD7uKgtA4tpABAoz8UM8VSA+D07o6sFY9TNHT3BLo3ku8SKxT1BeSRKchXWvdYcINQG16KF0fEolyUCziij22kXnaI0gauogXbDz/TXdS1D5rn7E/neJpBXpLAzxQ+KrUeaTPxuDxaYonkPufAOLxQt7qE35dlCmVrpaVmZzrNrvLZRAoS8AYbgRXIkiVHvkVFoPMNlEMNDRy5YRzC5PkMKP5GLLFx2eFuCxHMn6vuSFXRTpgrdawOqmf7rcMqd0t5z+r6AAft0teh7p8ThsDL7tRKSatbgUB0SusN1uRYYamPyykFD/sWAjcD0E+922wO97hV+kMfqr58yqinh4=
  app: tony-devops
  edge: true
