language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: cK7EzHote4LKwgf/Jvk2RGd1BPNdRGsJ5PmCNwQHxz3d81XdctPUlbGXC9foxoC7N2Oz3ksO9Ifk4sFgo+B31/BIEIjhyYMN9B0ZkxgegfkBKxdN8GFfm0m5To04qdOkEhj5mWB7E9SQqVH55lnDeyqyhSob3cbD2tVC9mZzWd32sAhjVjoi+PFj8a5fM65umgL9TA/LkfPyFBMnO7F6KHHLOyAzxeswo9DCmLrLmSfTQ1CJiildK8EheYRhcM+ClX3Agqy1w4Yrbnhh48gQeHTHEeKTiqYUMFhHpq5vArdgH3LPl52HQz0C/fSrE/6uHTegJ4PoZOcQTXMp0p9vZHalQ4j/+fz0+Q87jU13InLTiAj9HU0n8GEh4Rz1rZX1s2qqJ+h5oB2lDAHuMTFdNZB8fWTJXBqi7fOSlnMgccqUbmCX7SXbGFxN+NktgtIbtKbgsdAZqhPP9ZUZH/sxgw9IntpYqT9WAw8IOpyZ6iINEMF1xLi7ny8R0P3l6THmj6D/puDG46QfaMclLGMkcBmCvm6Qqf8B5XPIc76ghPyjGOfGqA+3n9nNRX/okUetCjOA9YRRaE9IVo0btAS92AA/FJ+o3To2oWQTDwQZbSmRSUZror0fA5TSx/3iW66oVgdMyo3I7UIua1NUULc+0fUAZHTB6QPm9qEy2tyDUKs=
  app: tony-devops
  edge: true
