language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Zz87zC3H/e4KVSAOHzKFWY0kY7+3SwPyhcb6x6Q0zLnxQJzvgU4CsHFH2t3LQgAVUTdH+BDEwTKU7kIzh899faxWKF6iDBb6mKAYzheQMegloRlHO7rkTswOhXtFsj5kE8T394AF1BquFG/nNTIGqgpkm5wGmoMicbQuFCPGf5dstOkvL7jdv1XZ/81rvBUw8Re0cxE1HaIkZ+KT8khn0woEIv68BhWpyL4dEUtTPoCo2piv5bCdZt7NJK9Bz5J1wIcEoJaJta9pTPo3H510p0B38OU6y+rSvfc2V9DjK9WDzyQQZzjLmZ1tae71lPcxJlFpaPR6lLHEWTsNXtYNNh0FGInl4iMojDCLyr0YajM9quAyX1A1PBka2VRoWlbYVDyC7A0znsA+OXl7Y+lSkDtn2VO0aQ9nLQ2RMkRGLBcrnzPlMw5YZAHHL7E4dJvFPHuKziSzFMuAffFWXARf84WvN+5lQisxlsQtrt9C7x7qGqjO0aMI7jM8E+h+Iw20LZrIXZFyuAa7/r+IGMHtfVmeuz/EINbk/mbSiN4x5ub+lyjlrLdktoGecw+ZTD8X0tpcHBL+aMKG0nQR2NUlzAFti4/RWSj5Xw+YP31z+jGqdCIEaZyl2OJzYPCLybe2jffT6R6IzxJKYnj9H3WrufA2OCoLxCv73jOKt02I9Us=
  app: tony-devops
  edge: true
